image: docker:latest
variables:
    REGISTRY: registry.gitlab.com/epay8223444/epay-admin
    IMAGE_NAME: $REGISTRY
stages:
    - build
services:
    - docker:dind
before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN $REGISTRY
build-image:
    stage: build
    script:
        - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA .
        - docker push $IMAGE_NAME:$CI_COMMIT_SHA
        - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:latest
        - docker push $IMAGE_NAME:latest
    only:
        - main
